# Generated by Django 3.1 on 2019-11-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='No Description', max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, default='No Description', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, default='No Description', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
