# Generated by Django 3.1 on 2019-11-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191126_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredientUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=1.0, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Unit')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient', 'unit')},
            },
        ),
    ]
