# Generated by Django 3.1 on 2019-11-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recipeingredientunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredientunit',
            old_name='value',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='unit',
            name='is_actual_measure',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
